### ISSUE TITLE
Out-of-date - consider removing?

### ISSUE THREAD

**Issue by mgleason** [nkolban/curl-esp32#3]
Just wondering of this repository is out-of-date and whether it should possibly be removed or made private?

The logic is that nkolban has become recognized as an expert on the ESP32.  Folks new to the ESP32 ecosystem might incorrectly assume therefore that this repository has been made specifically for the ESP32 or that might compile more easily for the ESP32.

**Comment by nkolban** [comment]
Sounds good to me ... removing now
